### ISSUE TITLE
Опубликовать библиотеку в хабе

### ISSUE THREAD

**Issue by yuriybylinkin** [Nivanchenko/winow#11]
Неплохо было бы опубликовать библиотеку в хабе
Чтобы можно было установить через opm install winow

**Comment by Nivanchenko** [comment]
Всему свое время.
По хорошему в хабе тогда нужно опубликовать еще autumn. Ее там еще нет, кажется по причине того, что есть много любителей opm install all. А осень работает на последнем оскрипт 1.8, и это может поломать установку. Я могу собрать в пакет .ospx и можно будет скачать и поставить из файла opm install -f winow.ospx. Но так же нужно будет еще ставить осень.
И для того что бы корректно работала обработка соединений через ФЗ, нужно будет после принятия ПР https://github.com/oscript-library/asserts/pull/10 обновить assert

**Comment by Nivanchenko** [comment]
winow в хабе. библиотека ассертов тоже обновлена. Осталось только ОСень донести до хаба.

**Comment by Nivanchenko** [comment]
ОСень теперь тоже в хабе.
