### ISSUE TITLE
Непонятность с точками маршрута

### ISSUE THREAD

**Issue by yuriybylinkin** [Nivanchenko/winow#12]
Воспроизвожу примеры из ридми.

```
&Контроллер("/greeter")
&Желудь
Процедура ПриСозданииОбъекта()

КонецПроцедуры

&ТочкаМаршрута("getparams")
Процедура Приветствие(ВходящийЗапрос, Ответ, Сессия) Экспорт
```

Так не работает - при открытии страницы 404, Страница не найдена

А вот так работает:
```
&Контроллер("/greeter")
&Желудь
Процедура ПриСозданииОбъекта()

КонецПроцедуры

&ТочкаМаршрута("/greeter/getparams")
Процедура Приветствие(ВходящийЗапрос, Ответ, Сессия) Экспорт
```
То есть в точке маршрута приходится писать полный путь 
Это справедливо для всех примеров

**Comment by Nivanchenko** [comment]
Да была проблема со слешами на Windows ОС. Поправил https://github.com/Nivanchenko/winow/commit/a6da0113d2cb2c35382969e5844f848a021f2c3c
